language: go
# check 1212
# see https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
# for the detail
# sudo: requried
dist: trusty

go:
  - 1.11.x

env:
  global:
    - MULTUS_GOPATH=${PWD}/gopath
    -   secure: "rino1hhWlxEO24xu/o8nyDm6/tHVN/MvyUhfWoCCGkQdtaLioCuIPw3SYowOCAC3Xbo0SDkWjRiK90aRllqrA4Ytu2kAJaqhbq1HFQnIISLF04tDnM4Je4cyk8+CHjgWhhX2a99cQfDeaPLfO01MAPVc+/pYnJ8T2RTF0j2Vofi229HhqegReCMtRmRIuWy8qPK2k0GhvGegSAaTwlbSZqoLbfBbq2tEbyFiA3k7pgMks1wZylxyNzgk5y7JCtNdUbNm7G0B7XLNgWbMwft/l9fm9/N7eLAfWK9z+/mA3van6OS7c9O72N2WcGg/MkGn6EkFr9VOaeLSZbxMwQeaRaCLKyl2e1j2FGx1f0xFAZQWzbXchW2Ea6QgZW4+2/4osTcgo+TOMv2WkJseJxyZ6xVwvCQaCMYS+EsPsnhcoURBFltkmnXN2NfXLGJDB+52GrWtCRQpUIbUwy1sdWbkrkrzmPq2rYNaWeVK+abHwRapBrJg0WOKJNl9WnFG/g8yJ/5MNzlD5MLVq8/sa7SvtvurT9kF1GFGutaJlH4ZDjXrogoy7Q4CEeFpYHK9J49a4MqKgfI0/Ykop8Jg0KJwN1yriKjS6huJQyYfT/PZM7alF6Kr5KoFw6d8Jkk4WGqpl+L64OX4aueSrBHBXdtAO3z3y4OcoWY05SNxySlJTYY="

before_install:
  - sudo apt-get update -qq
  - go get github.com/mattn/goveralls

install:
  - go get -u golang.org/x/lint/golint

before_script:
  # Make gopath... to run golint/go fmt/go vet
  - |-
    if [ ! -h gopath/src/github.com/intel/multus-cni ]; then
        mkdir -p gopath/src/github.com/intel
        ln -s ../../../.. gopath/src/github.com/intel/multus-cni || exit 255
    fi
  - env GOPATH=${MULTUS_GOPATH} golint gopath/src/github.com/intel/multus-cni/multus/... | grep -v ALL_CAPS | xargs -r false
  - env GOPATH=${MULTUS_GOPATH} go fmt gopath/src/github.com/intel/multus-cni/...
  - go tool vet */*.go
#  - gocyclo -over 15 ./multus

script:
  - ./build
  - sudo ./test.sh
  - |-
    GOV_GOPATH=${PWD}/gopath
    pushd gopath/src/github.com/intel/multus-cni
    env GOPATH=${GOV_GOPATH} ${GOPATH}/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    popd
  - mkdir -p ${TRAVIS_BUILD_DIR}/dist
  - tar cvfz ${TRAVIS_BUILD_DIR}/dist/multus-cni_amd64.tar.gz --warning=no-file-changed --exclude="dist" --exclude="vendor" .
  - docker build -t dougbtv/multus-defaultnet .

deploy:
  # Push images to Dockerhub on merge to master
  - provider: script
    on:
      branch: default-per-namespace
    script: >
      bash -c '
      docker tag dougbtv/multus-defaultnet dougbtv/multus-defaultnet:snapshot;
      docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS";
      docker push dougbtv/multus-defaultnet:snapshot; 
      docker push dougbtv/multus-defaultnet:latest; 
      echo done'